server:
  port: 8000
spring:
  rabbitmq:
    host: 49.235.110.134
    port: 5672
    username: admin
    password: admin
  # redis缓存
  redis:
    host: 49.235.110.134
    database: 0
    port: 6379
    password: lovingliu
    timeout: 3000ms
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
zuul:
  ignored-patterns:
    - /product/**
    - /order/**
    - /user/**
  routes:
    myProduct:
      path: /mallProduct/**
      serviceId: product
    order: /mallOrder/**
    user: /mallUser/**
    activity: /mallActivity/**
# 注意就算把下面的配置删除/增加，不重启项目项目没办法起左右(@RefreshScope)
management:
  endpoints:
    web:
      exposure:
        include: "*"
redis:
  auth-code-prefix: "username:%s"
  login-token-prefix: "lovingliu:%s"
  auth-code-expire: 120
  login-token-expire: 604800
  order-lock: 10000
  user-cookie-key: "lovingUser"
  admin-cookie-key: "lovingAdmin"
# zuul统一异常处理
error:
  path: /error 
