server:
  port: 8000
spring:
  rabbitmq:
    host: 49.235.110.134
    port: 5672
    username: admin
    password: admin
zuul:
  ignored-patterns:
    - /product/**
    - /order/**
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
    order: /myOrder/**
# 注意就算把下面的配置删除/增加，不重启项目项目没办法起左右(@RefreshScope)
management:
  endpoints:
    web:
      exposure:
        include: "*"
redis:
  auth-code-prefix: "username:%s"
  login-token-prefix: "lovingliu:%s"
  auth-code-expire: 120
  login-token-expire: 604800
  order-lock: 10000
  user-cookie-key: "lovingUser"
  admin-cookie-key: "lovingAdmin"
