server:
  port: 8000
spring:
  rabbitmq:
    host: 49.235.110.134
    port: 5672
    username: admin
    password: admin
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
# 注意就算把下面的配置删除/增加，不重启项目项目没办法做任何更改      
management:
  endpoints:
    web:
      exposure:
        include: "*"
